---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-linters
