---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
    check:
      jobs:
        - stx-upstream-tox-pep8
        - stx-upstream-tox-linters
    gate:
      jobs:
        - stx-upstream-tox-pep8
        - stx-upstream-tox-linters
    post:
      jobs:
        - stx-upstream-upload-git-mirror

- job:
    name: stx-upstream-tox-pep8
    parent: openstack-tox-pep8
    nodeset: debian-bullseye

- job:
    name: stx-upstream-tox-linters
    parent: openstack-tox-linters
    nodeset: debian-bullseye

- job:
    name: stx-upstream-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/upstream to
      github.com/starlingx/upstream
    vars:
      git_mirror_repository: starlingx/upstream
    secrets:
      - name: git_mirror_credentials
        secret: stx-upstream-github-secret3
        pass-to-parent: true

- secret:
    name: stx-upstream-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - yqX7yOFWM2+nq3F90Hvqax5PHhEXi1mPV8G+YB3CKsH6trHrKLPYuw7cxL1ago5zf7DsR
          hTojfjskWc0zNrKMVr99munhtwar10uSnx7jzQE10eD7vHpUQbUTbyGTLipxlsYn14PO5
          1vwX8KkkZ3zlcYo2c2z6wGok4fRQUNScBLyOxxTxiBeJaC7bY9DY02ofW8BwaIij9O8U2
          gzTPyXrBH+zlgeTm7zcw7fw3jsznuojWoEu+SqiobVvtOXQT3C7kmDgOuByBDzcEefmpd
          x1kBjInDJbcGbVcgQ5dno8RX1KaMueJUDuoo306CJzx2GHqG8+Ug/niCzcUCwxeSejlFM
          b3VSTsv6kXdgn5bx1t6lgDrfZ3nDVZRZ5/5rlaa92qldOnrbFnjEm0D8BpODk+8pHaoo2
          wmd0hOUzPbY1Y3KNddnxemXOTXcsLWv1CK9l9wJr1b8HKrsFbyBXT8Mk0aAY+ZBHccu0g
          31uSOCj4ifIJkBJjDCau5DgR/SXv+FpXwGIbw5S3cJpNHFN+KJ2bs35cAbXdvG6yaXLfe
          OjqksaJ+u1cNPf017y8Kddr11yHwAw6/iLG7/1HEjT3Z3l10zy0riPesb26CwZUksQNMj
          w+SkX8Xld2fqnN1mUpIBrhUAHEug3ne8QXlbb+3nB4yhF5SD5MpK0q0Tcij5sk=
        - tw7BvHbWMZk7rOxAxUNuj84gOfeqsWjoy+MuGqU24fSScdWX6jW3MaG4MLuRN9qJlqyPL
          4vYjO2FhY58bSVuTjcqUF4cqB9H/uUmYVdfohJtKfy8dMtauWaVnyvgrspVEC1cygHm2a
          xhC0+OAYw+639iEn/e0B0lzpm6XUVYYjOywuhjCJ4b0nbcUMqEmc2bIJ47XTPLW3XDUVT
          BPtzJX6ylNO5jl/4kaYg4QLaOIIVkLHkPjsNI8YUFU2JIvas2O2OkZDNVKoFzWIO2jUoX
          UwEey3VIj4SxhBuhukk1HwkKSlUnRIPe6v7tvdO6ET979nOoRk2H2Uyc6lTQNespyGlXY
          O/DKWFIj2pbKRh7sCeYVpvGXrUrKjEtLYTC0VI3C1J0XKOIw01QzrKYWJku9cTocDZBEV
          QLY80D92wBAM3WHd+zxawE5Josy+0zu0IwObo7SFKcmyybuvuNeDFq7c4m5JK6SWf/oFT
          rJ+FJnxOQsSTBmMUJtPkhGaCFim8jnIwnw6S7/YDwoHKcWGaNjobnbLwInJwHR3rH74VK
          KcLmzhC5hHDNb/qnLLeeqpCkA0bpiEZHBLp3cC9ts59no6KHTvMC/t1tUbztCNz3WkGcp
          mAoIk2tVZp+ag2vchF3YRmZuCid9msIp3y9vFO9hB0KJETZYJcJNnSamAz5pzg=
        - Zsl9xuQw675bN3MspeQgk+IzBXxqY/JKVHbVV1mY1W0LhhtLIGw52oEYqLkuUGAImNeDG
          V57fbbsRNbLsopbNxxKrc7u9wLy0HuZ881nRyN+qscW0TjuEFT7AVic2OAFMAAOD98OfY
          Oh1TzLKK/AQmqdCQhj3arGBaDPE0QMVJZtw+BzWtVZd64oLMjWlGKIX9zF8LIVN9+g1BJ
          XU8ea1+Wxty4V0D9QKUuflhvGfcPEHpQ2ZF1Z4PmEM8EFnct2w3tNMKLS00zPu8XPHa8f
          DpIqh8UA3eqE1hMzbAqV8OkEytk12qMlQJMCbHDyfk/0sijGwJmZ1hjjg4SNd2BVOHmL2
          6weQgPMkb8eWCN85frZXDR2OoQJf/wGXRG2/3IsskvdtqQ6ODqsGncKz9y2EwtY/IdOzr
          qGWybc+HVLmVxWzfg0WIGLy2XJ1+arQHCYhpAyYh51FDjJ5CcrQ63sp6i9sRBeLfoqLUE
          8KtCTo7ogO6d6cs6Rd7knPLvf2XhMhXynZyf6LIddG9W/xgHzCV6frZ2J/Wy3X4SA7Bdm
          lfz1sGNEx/n9vutv8R7XfO4fbB7Omzu7CYop6LvCoYN68optqiQnFFS1WzSemLeZJbqDO
          ABknv6lFMo/ASYP6Y9/TDfH/pRdYI0hMCai80QdzJvM/kFSI7efdmT39YQlH1w=
        - 3400M/aSg5ZCog3ur5Fmn3Y0Fyx86s89RzK59qTEYsLoRuMZt1U+mQU5GYOLHVOZQHu0i
          4Jr2DhjHDIThj7C2P63Vvkew7u/3VZqlmofxKjHHT05wT+Lvg4Ewk8ZgMAmtrwQe2rRwH
          pTNpE8xWiT2+aEtr4qZT2Es0ipMIS9jnNjhH4wK19Rgzmd7nPC+olMNWHUKcg2mqbQA+d
          SHf2PqfHuqvHnr3hK6D1P+qXeih4b7MiJ3nU+KW3450CIAR2csMeFp7dkfh9fzCBM+qmV
          tcgFreosDE08wIc2fH207vpbWRR3axiZ6kb2slQQK14WTwu2ADGbadQMRSjOrKHMPwYmG
          AT6bwgqNJxkZGvJ7/+FCgPzAx5V0jOH22L7aGG+dc025E9wWoQadLHrBfw4+q+9pZRhS/
          P+nj3vBgKvrVPxXoruYEjM9VHxhvGa1tTFzRdlTXamTNJRJcMy3wCV6hGzza5qI82sfNW
          nrk7eENp3AOrVR0VCAvu0FW6PLcxX0adhc05q94umG1d3ru8jsMfxeJeRworokfr3GN73
          7cvoGf3RqW+2TMb5+RZRrpuklN/vTphEPzfaBL7jalvUpR+K/DDNc4ZT6i30pDyjv1ahO
          z1h0ECWjD7xzrNrflRs2dA6CN95awKErm79eXnyACuduzLgzF3meQmJEV/Layo=
        - 2aB/7uGfq+VpPqb1POYvuYn6qHCMm+GjjPnHUpmzqXmf5Apus9No6hO5GOwrrTlGWE4XP
          xZ/b3a6GPQZeR1m8QsOHeMCC0DFciUS2NDjzLOK4yfqYR1J2d+MBNpCsSQ4dycIPR3Ks5
          uYbT4LjIBRG5D2vBFbZUgKbF2P2q9Ih5Er/tN7EzAnLtfxe6SqyNqfDWWnMDj9FD1DZDK
          DQfzAXa69vcHi85Y/T6LWLgZXXAnWjuUYTdsQniX6vAMyQiIrRd9FHfzS6fGhz7oO8Vv5
          W/+PBttB8uznSGSenLe8s3VNFLMFp6wNwTYbRQoVKFLK3yYt3WeKUmwpOjWlfgEq6eVIS
          /Mbe3sNFlJ1donp4CgOZOGxwLn0He6yEB8b76uhMwIq8bRV8uNEk4ABSmjxKw7KhixPBQ
          frssm3dvaf0KZmua+45iCArBSjHWCMjUBe9W1kUHpNacW6rY6xjr5qa/z7OAddmVLR5dB
          Xlqt6KaZBo6tv3KoZFo5XJ6R3JDvIJrLKyrHMZYjs6S95Rm5Z3exey4G3q0o+FYtdXTlj
          G7+iiwsL+KP/jLjSHapr8b2Z7ZZwNEpnCyBkDOfuC8AQWJxQig4a2LPMflk0/QdsDHb0W
          Jmb86hgZRNAxaOaj/ErUgcCliW/AFdYoqQZGVapOrdI4IJ9DrDz+ZH8KqO3lt0=
        - JeLTBSolISB73lyvWwJp9+KDuj4qbs0entcykbKL0H4TQUuYYNjfsvOuS+WxiOeBsKtKy
          F8i0MtMX+gtT4xEnY7cXOyQTtHwTDVLvfP1EEZRKkJkRi9ZmM6/PH4i37xOfAanw4rZe3
          an6XkxXC4LkYudt0+8dImo83/7xJES8WMPhiBLJlPEkORTf/XgycqE2K56qKkXbdaZoZN
          QctA5JS7BWW2rU/3/l3Gpp+9o5cZYIfiaRA1s1HvD1M4W2lopFukX2UkrCeYbYkdbYraK
          udXNBOsNwEzUDZ8sOTiFk0hB5doZ1fhlIFws3HlQVYD9KQR96vWUidBdD8tH3WqGB895T
          gwTuRhANwnmBf5MojUMSMabQz+loDw7+VRSA30H6uGnk2Ory7YO33yH6JzDfNCRnRokKa
          RBjplJevu/HM+ohag+eAO22zcycu5PMyPhJLbmk3VdiZ2wstzoUDDc0SN5bfZ8GYx1h8F
          sGm36mbW2YHNvyZUyTC1LXOSHe3BSw9xmzIUNW6jKdNrrM8dUgBiZ4f/u/lVCVYYLdDcJ
          HyOzRykLwyaVn6WrhKPxBpZtvGXnnR8715mj1G47pZ6xOLzPY110N3FSHew3/4lIbKsIE
          O793O6oF134okzG0Yga3UtubeuyZtkUYTTr5idTkJAUS25c7eIsuf5QKKdbg88=
        - hMWPDGH9kzrsMHwSkllhLgI7V23rOSBmllCWfMdQBxHuc++aAUQn6xikJBAyIcKhQpbfZ
          /ue5jY6wwmfn2/79cc2lLXToqIYoSsSV77iZjSptr0Nm7zNm1daSL3irOI4NlAyoTUpVd
          kjFEzL3x550wUeWtN1LqBQ0tte68ueq5XQnftUjXA0AS5b2kraqJ8Bh8V2JlhzgG8U9P/
          SDHu9YGlTty3HbSBYb80PKW79GcrQuCkOa6vWozdRnPZXYDzORlydCiDJTtcwWqA39TFT
          WlKYHSHc3nGS0K7ARfd5LZPnOuxJi3i9sdxFTTFk/PtNxdMGQh57EKVVTq5pG9wYKIkAG
          U3a+938rwBL9bzkhrkG0W9jEAa7MWlp6RpCL22jNXPOIbTNI/tSd+p6WsyGkMMiIvvkTF
          5j4yVNRtFLirGjYXSH+ddN1L+fCt/SSPlV2yYtMc+S2lwkxzlNyEuL4TI9ZdMHEHGv0Kb
          Zo4UsB0xflADPC1CocTUmOIPVUbGWbXQPOmFnFxVNrMi+Co30CdqKC5Y51HMlhg8eqmZ+
          lPOgM4qh/Q5rCcZ6/amVwgC/5JhhYFqUU+JVK3weyIpE4RtaBvRu2T2TarxTyd92F7qui
          vh81UHG2ogsa73iwswTzjIb2n7LIUTbX41lwBoJ/NWh4JXRKRfmGH6FWNZck8U=
