# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# ceph
#ceph
#ceph-common
#ceph-fuse
#ceph-radosgw
#libcephfs2
#python-cephfs
#python-ceph-compat

# ceph-manager
#ceph-manager

# openstack clients
python3-aodhclient
python3-cinderclient
python3-glanceclient
python3-gnocchiclient
python3-heatclient
python3-ironicclient
python3-keystoneclient
python3-neutronclient
python3-novaclient
python3-openstackclient
python3-pankoclient
python3-swiftclient

# openstack-ras
openstack-ras

# python-django-horizon
python3-django-horizon
openstack-dashboard

# stx-dashboard
starlingx-dashboard

# openstack-keystone
openstack-keystone

# rabbitmq-server
rabbitmq-server

# python-wsme
python3-wsme


# openstack-barbican
openstack-barbican
openstack-barbican-api
openstack-barbican-common
openstack-barbican-keystone-listener
openstack-barbican-worker
puppet-barbican
python3-barbican
python3-barbicanclient
python3-ldap3
