# List of packages to be included/installed in ISO
# If these have dependencies, they will be pulled in automatically
#

# ceph
#ceph
#ceph-common
#ceph-fuse
#ceph-radosgw
#libcephfs2
#python-cephfs
#python-ceph-compat

# ceph-manager
#ceph-manager

# openstack clients
#python2-aodhclient
#python2-cinderclient
#python2-glanceclient
#python2-gnocchiclient
#python2-heatclient
#python2-ironicclient
#python2-keystoneclient
#python2-neutronclient
#python2-novaclient
#python2-openstackclient
#python2-pankoclient
#python2-swiftclient

# openstack-ras
#openstack-ras

# python-django-horizon
#python-django-horizon
#openstack-dashboard

# stx-dashboard
#starlingx-dashboard

# openstack-keystone
#openstack-keystone

# rabbitmq-server
#rabbitmq-server

# python-wsme
#python2-wsme


# openstack-barbican
#openstack-barbican
#openstack-barbican-api
#openstack-barbican-common
#openstack-barbican-keystone-listener
#openstack-barbican-worker
#puppet-barbican
#python2-barbican
#python2-barbicanclient
#python2-ldap3
