# List of packages to be included/installed in ISO

#barbican
#barbican-api
#barbican-common
#barbican-doc
#barbican-keystone-listener
#barbican-worker
#python3-barbican

#keystone
#keystone-doc
#keystone
#python3-keystone

#python-barbicanclient
#python3-barbicanclient

#python-horizon
#horizon-doc
#openstack-dashboard-apache
#openstack-dashboard
#python3-django-horizon

#python-keystoneclient
#python-keystoneclient-doc
#python3-keystoneclient

#python3-keystoneauth1

#python-openstackclient
#python-openstackclient-doc
#python3-openstackclient

#python-osc-lib
#python-osc-lib-doc
#python3-osc-lib

#python-oslo-messaging
#python3-oslo.messaging

#python-wsme
#python3-wsme

#rabbitmq-server
#rabbitmq-server
