# List of packages to be included/installed in ISO

#barbican
barbican-api
barbican-common
barbican-doc
barbican-keystone-listener
barbican-worker
python3-barbican

#keystone
keystone-doc
keystone
python3-keystone

#openstack-ras
openstack-resource-agents

#python-aodhclient
python-aodhclient-doc
python3-aodhclient

#python-barbicanclient
python3-barbicanclient

#python-cinderclient
python3-cinderclient

#python-glanceclient
python-glanceclient-doc
python3-glanceclient

#python-gnocchiclient
python-gnocchiclient-doc
python3-gnocchiclient

#python-heatclient
python3-heatclient

#python-horizon
horizon-doc
openstack-dashboard-apache
openstack-dashboard
python3-django-horizon

#python-ironicclient
python-ironicclient-doc
python3-ironicclient

#python-keystoneclient
python-keystoneclient-doc
python3-keystoneclient

#python-neutronclient
python3-neutronclient

#python-novaclient
python-novaclient-doc
python3-novaclient

#python-openstackclient
python-openstackclient-doc
python3-openstackclient

#python-openstacksdk
python-openstacksdk-doc
python3-openstacksdk

#python-osc-lib
python-osc-lib-doc
python3-osc-lib

#python-oslo-messaging
python3-oslo.messaging

#python-pankoclient
python-pankoclient-doc
python3-pankoclient

#python-wsme
python3-wsme

#rabbitmq-server
rabbitmq-server
